name: Build Test

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v4
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
      - name: Compile
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force build/classes | Out-Null
          javac -d build/classes Test.java
          jar --create --file build/Test.jar --main-class test.Test -C build/classes .
      - name: Make the Windows app
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force dist | Out-Null
          jpackage --type exe --name Test --input build --main-jar Test.jar --main-class test.Test --dest dist --win-shortcut --win-menu
      - name: Save the EXE
        uses: actions/upload-artifact@v4
        with:
          name: Test-Windows
          path: dist/Test-*.exe
